#-------------------------------
# General Site Settings

title: Frêne & Scie
description: >
  A finalité sociale, Frêne & Scie est une société d’ÉCO-MENUISERIE spécialisée dans la confection de yourtes et l’aménagement d’espace extérieur.
email: contact@frene-et-scie.be
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://frene-et-scie.be/" # the base hostname & protocol for your site
favicon: "favicon.ico"


# NOTE: The Logo and Background image are defined in the all.sass document.

menu:
- {name: Qui nous sommes, url: '#about'}
- {name: Services, url: '#service'}
- {name: À la une, url: '#agenda'}
- {name: Contact, url: '#contact'}

#-------------------------------
# SEO Section

# NOTE: Providing SEO information will make this website more searchable on the internet.

seo:
  description: 'Provide a description for your website to make it visible to search engines.'
  rel-author: 'http://oliviercleyman.com'
  rel-publisher: 'http://oliviercleyman.com'

#-------------------------------
# Google Analytics Section

# Analytics helps you understand who visits your website.
# Learn more at: http://support.google.com/analytics/answer/1008065

# NOTE: If you want to use Google Analytics for basic web tracking: Just uncomment and enter your UA-Code here.

#google-analytics-ua: UA-XXXXXX-X

#-------------------------------
# About Section

# NOTE: The avatar is defined in the all.sass document.

blurb: >
  A finalité sociale, **Frêne & Scie** est une société d’éco-menuiserie spécialisée dans la confection de [yourtes](#service){:target="_self"} et [l’aménagement d’espace extérieur](#service){:target="_self"}. Par son travail de création, inspiré du savoir faire ancestral [kirghize](#service){:target="_self"}, **Frêne & Scie** propose des structures variées en forme courbe, du pavillon d’été à l’habitat permanent. Par la technique du [cintrage à la vapeur](#service){:target="_self"}, le bois d’essence locale est assoupli en vue de lui donner les formes désirées et d’assurer un rendu plus organique. Le feutre de laine du pays, utilisé comme couverture extérieure, assure une intégration harmonieuse de la yourte à son environnement. Yourtes en clé sur porte ou en accompagnement à l’auto-construction, **Frêne & Scie** invite à et milite pour un renouvellement de l’Art d’habiter.


#-------------------------------
# Service Section

services:
- {name: Yourtes Kirghizes, id: service1, url: '#service1', description: 'Lorem ipsum dolor sit amet, et assum efficiantur his, tota postea moderatius ei eos. Eam quis percipitur sadipscing cu. Sale liberavisse ius te, laudem disputando has no. Eos platonem assentior ut, ea iudicabit gubergren evertitur ius, eum nobis definitionem ea. Vix eu quot quaerendum efficiantur.'}
- {name: Cintrage Massif, id: service2, url: '#service2', description: 'Et inermis copiosae cum. Illum delectus voluptaria his ne. Habeo saepe tantas sed no. Ei duo solum pertinax. Ludus aliquid honestatis et pri. Est habeo singulis hendrerit cu, graeco scriptorem theophrastus est ne. Mea audire interpretaris an.'}
- {name: Éco-Menuiserie, id: service3, url: '#service3', description: 'Odio denique conclusionemque eum et. Pro quodsi expetendis adipiscing ad, vim posse nominati id. Et laboramus assentior quo. Idque dicant verear pri te, vim ad simul dolores, iusto constituto per eu.'}
- {name: Espaces Extérieurs, id: service4, url: '#service4', description: 'Mei menandri definiebas ad, aeque omnes posidonium ut ius, ut modo justo intellegebat mel. Hinc lucilius detraxit eos at. Hinc inimicus volutpat at his. Ius ornatus convenire honestatis at, ei wisi ceteros pro. Timeam aliquam mea no, ad autem semper vis. An invenire voluptaria eam.'}

#-------------------------------
# Work Section

#-------------------------------
# Clients Section

#-------------------------------
# Contact Section

social:
- {icon: 'twitter', link: 'http://twitter.com/frene-et-scie'}
- {icon: 'facebook', link: 'https://facebook.com/frene-et-scie'}


# social network icons available: 'twitter' / 'facebook' / 'github' / 'pinterest' 'google-plus' / 'linkedin' / 'youtube' / 'instagram' / 'dribbble' / 'behance' / 'soundcloud' / 'vine'

#-------------------------------
# Footer Section

copyright: "Copyright© Frêne & Scie 2015"
dev-credit: Code Design 
dev-name: Olivier Cleyman
dev-contact: olivier.cleyman@gmail.com